### ISSUE TITLE
Shutdown immediately on Android 10 

### ISSUE THREAD

**Issue by Erik-Lehnsherr** [masavoyat/MicStream#7]
Dear Madam/Sir,

I have tried to implement this solution on Android 10 device.
However, while the app is initiated, it unexpectedly quits (crashes).
Any suggestions would be highly appreciated.

Thanks!

Best!

**Comment by masavoyat** [comment]
I am able to reproduce the problem on a nokia 2.2 with android 10.

**Comment by Erik-Lehnsherr** [comment]
Dear Madam/Sir,

Thank you so much for the fix!
If possible, may I know how to test the receiving function based on your code?
Any suggestions would be highly appreciated.

Thanks!

Best! 👍
