### ISSUE TITLE
Test method for receiving

### ISSUE THREAD

**Issue by Erik-Lehnsherr** [masavoyat/MicStream#8]
Dear Madam/Sir,

If possible, may I know how to test the receiving based on your code?
Should I use VLC media player to receive the audio stream sending from Android or maybe other methods are preferred?
Any suggestions would be highly appreciated.

Thanks!

Best! :)

**Comment by masavoyat** [comment]
Hello,
you can find an implementation of stream receiving and decoding here: https://github.com/masavoyat/MicStreamServer/blob/master/UDPStreamReceiver.py
